#!/bin/bash
set -euo pipefail

echoerr() { echo "$@" 1>&2; }

get_token() {
    set +u
    token=$ACCESS_TOKEN
    if [ "$token" == "" ]; then
        token=$(cat /etc/spotify-oauth/access_token)
    fi
    set -u
    echo "$token"
}

sp_curl() {
    echoerr '[DEBUG] curl -s -H "Authorization: Bearer XXX_REDACTED_XXX"' "$@"
    curl -s -H "Authorization: Bearer $(get_token)" "$@"
}

now_playing() {
    sp_curl "https://api.spotify.com/v1/me/player"
}

devices() {
    local d
    d=$(sp_curl "https://api.spotify.com/v1/me/player/devices")
    # After n+1 time units of debugging dj-kubelet decided that it's of great interest to print the devices response.
    echoerr "$d"
    echo "$d"
}

has_active_device() {
    devices | jq '[.devices[].is_active] | any'
}

disable_repeat() {
    # $1 = device_id
    sp_curl -XPUT "https://api.spotify.com/v1/me/player/repeat?state=off&device_id=$1"
}

play_track() {
    local track="$1"
    local device_id="$2"
    sp_curl -XPUT \
        "https://api.spotify.com/v1/me/player/play?device_id=$device_id" \
        --data @- <<EOF
{"uris": ["$track"],
"offset": {"uri": "$track"},
"position_ms": 0}
EOF
}

find_device() {
    # Play on the currently active device if the user has one
    if [ "$(has_active_device)" == "true" ]; then
        echoerr "User has active device"
        devices | jq -r '[.devices[] | select(.is_active).id] | first'
        return 0
    fi

    # Play on the first device found as a fallback
    echoerr "Trying to play on the first available device"
    devices | jq -r '[.devices[].id] | first'
}

play_wait() {
    play_track "$1" "$2"
    local started="false"
    while true; do
        sleep 2
        np=$(now_playing)
        is_playing=$(jq -r '.is_playing' <<<"$np")
        playing_uri=$(jq -r '.item.uri' <<<"$np")
        remaining_ms=$(jq -r '.item.duration_ms - .progress_ms' <<<"$np")

        if [ "$playing_uri" == "$1" ]; then
            started="true"
            # Maybe continue since not started yet?
        fi

        # Is the track done?
        if [ "$is_playing" == "false" ] ||
            [ "$playing_uri" != "$1" ] ||
            [ "$remaining_ms" == "0" ]; then
            echoerr "Track is done: is_playing=$is_playing playing_uri=$playing_uri remaining_ms=$remaining_ms started=$started"
            exit 0
        fi

        track_name=$(jq -r '.item.name' <<<"$np")
        artist_name=$(jq -r '.item.artists[0].name' <<<"$np")
        echo "$track_name - $artist_name :: $remaining_ms ms remaining"
    done
}

DEVICE=$(find_device)

if [ "$DEVICE" == "" ]; then
    echo "No player devices connected!"
    exit 1
fi

disable_repeat "$DEVICE"
track="$*"
echoerr "$track"
play_wait "$track" "$DEVICE"
