apiVersion: v1
kind: Pod
metadata:
  labels:
    dj-kubelet/spotify-track: ""
  name: track3
spec:
  restartPolicy: Never
  containers:
  - image: spotify-ctl:latest
    name: track
    imagePullPolicy: IfNotPresent
    args:
      - spotify:track:4YhN72dRYL2Z3MsaKyT7rS?context=spotify%3Auser%3Aspotify%3Aplaylist%3A37i9dQZF1DWTh5RC6ek3nb
    volumeMounts:
    - name: spotify-oauth
      mountPath: "/etc/spotify-oauth"

  volumes:
  - name: spotify-oauth
    secret:
      secretName: spotify-oauth

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: dj-kubelet/spotify-track
            operator: Exists
        topologyKey: "kubernetes.io/hostname"

